# Generated by Django 5.2.5 on 2025-08-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=255)),
                ('market_value', models.CharField(blank=True, max_length=100, null=True)),
                ('nation', models.CharField(blank=True, max_length=100, null=True)),
                ('pos', models.CharField(blank=True, max_length=50, null=True)),
                ('club', models.CharField(blank=True, max_length=150, null=True)),
                ('league', models.CharField(blank=True, max_length=150, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('mp', models.IntegerField(blank=True, null=True, verbose_name='Matches Played')),
                ('starts', models.IntegerField(blank=True, null=True)),
                ('minutes', models.IntegerField(blank=True, null=True, verbose_name='Minutes Played')),
                ('goals', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('penalty', models.IntegerField(blank=True, null=True, verbose_name='Penalties Scored')),
                ('pk_att', models.IntegerField(blank=True, null=True, verbose_name='Penalty Attempts')),
                ('yellow_cards', models.IntegerField(blank=True, null=True)),
                ('red_cards', models.IntegerField(blank=True, null=True)),
                ('gls_per90', models.FloatField(blank=True, null=True, verbose_name='Goals per 90')),
                ('ast_per90', models.FloatField(blank=True, null=True, verbose_name='Assists per 90')),
                ('g_plus_a', models.FloatField(blank=True, null=True, verbose_name='G+A')),
                ('gls_plus_ast', models.FloatField(blank=True, null=True, verbose_name='Goals+Assists')),
                ('sh', models.IntegerField(blank=True, null=True, verbose_name='Shots')),
                ('sot', models.IntegerField(blank=True, null=True, verbose_name='Shots on Target')),
                ('fk', models.IntegerField(blank=True, null=True, verbose_name='Free Kicks')),
                ('sot_percent', models.FloatField(blank=True, null=True, verbose_name='Shots on Target %')),
                ('sh_per90', models.FloatField(blank=True, null=True, verbose_name='Shots per 90')),
                ('sot_per90', models.FloatField(blank=True, null=True, verbose_name='Shots on Target per 90')),
                ('g_per_sh', models.FloatField(blank=True, null=True, verbose_name='Goals per Shot')),
                ('g_per_sot', models.FloatField(blank=True, null=True, verbose_name='Goals per Shot on Target')),
                ('tackle', models.IntegerField(blank=True, null=True)),
                ('tackle_won', models.IntegerField(blank=True, null=True)),
                ('tackle_d', models.IntegerField(blank=True, null=True, verbose_name='Tackles Defended')),
                ('tkl_percent', models.FloatField(blank=True, null=True, verbose_name='Tackle %')),
                ('press', models.IntegerField(blank=True, null=True)),
                ('succ_x', models.IntegerField(blank=True, null=True)),
                ('succ_percent', models.FloatField(blank=True, null=True, verbose_name='%')),
                ('blocks', models.IntegerField(blank=True, null=True)),
                ('shot_block', models.IntegerField(blank=True, null=True, verbose_name='Shots Blocked')),
                ('interception', models.IntegerField(blank=True, null=True, verbose_name='Interceptions')),
                ('clearance', models.IntegerField(blank=True, null=True, verbose_name='Clearances')),
                ('passes_completed', models.IntegerField(blank=True, null=True)),
                ('passes_attempted', models.IntegerField(blank=True, null=True)),
                ('cmp_percent', models.FloatField(blank=True, null=True, verbose_name='Completion %')),
                ('touches', models.IntegerField(blank=True, null=True)),
                ('succ_y', models.IntegerField(blank=True, null=True)),
                ('att', models.IntegerField(blank=True, null=True)),
                ('number_of_players', models.IntegerField(blank=True, null=True, verbose_name='#Pl')),
            ],
        ),
    ]
